---
platform: linux

params:
  STAGE:
  AWS_ACCESS_KEY_ID:
  AWS_DEFAULT_REGION:
  AWS_SECRET_ACCESS_KEY:

  # These are set for deploy.sh
  SERVICE_NAME: "authorisation-api"
  CLUSTER_NAME: "api"
  TASK_NAME: "authorisation-api"
  CONTAINER_NAME: "authorisation"

inputs:
  - name: src
  - name: deploy-tools

run:
  path: bash
  args:
    - '-exc'
    - |
      src/tasks/scripts/deploy.sh
